//ログイン処理
to login
	if ImageFound(Image:"BasicTestCase/GameStart" , WaitFor:5)
		tap FoundImageLocation()
		wait 3
	end if
	
	repeat 3
		if ImageFound(Image:"BasicTestCase/DoLogin" , WaitFor:5)
			tap FoundImageLocation()
			wait 3
		end if
	end repeat
	
	if ImageFound(Image:"GoToSchool" , WaitFor:5)
		tap FoundImageLocation()
		wait 3
		repeat for 120 seconds
			if imagefound(image:"MainMenuOnTop", waitfor:1)
				LogUtil.write "result", "Basic", "Basic", "login", true
				return true
			else if imagefound(image:"MainScreenHeader", waitfor:1)
				LogUtil.write "result", "Basic", "Basic", "login", true
				return true
			else 
				tap (RemoteScreenSize().x / 2, RemoteScreenSize().y / 2)
			end if
		end repeat
	end if
	LogUtil.write "result", "Basic", "Basic", "login", false
	return false
end login